<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />



<title>iperform</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>

<style type="text/css">
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
</style>



<style type="text/css">
code {
white-space: pre;
}
.sourceCode {
overflow: visible;
}
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
{ counter-reset: source-line 0; }
pre.numberSource code > span
{ position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
{ content: counter(source-line);
position: relative; left: -1em; text-align: right; vertical-align: baseline;
border: none; display: inline-block;
-webkit-touch-callout: none; -webkit-user-select: none;
-khtml-user-select: none; -moz-user-select: none;
-ms-user-select: none; user-select: none;
padding: 0 4px; width: 4em;
color: #aaaaaa;
}
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa; padding-left: 4px; }
div.sourceCode
{ }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } 
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.at { color: #7d9029; } 
code span.bn { color: #40a070; } 
code span.bu { color: #008000; } 
code span.cf { color: #007020; font-weight: bold; } 
code span.ch { color: #4070a0; } 
code span.cn { color: #880000; } 
code span.co { color: #60a0b0; font-style: italic; } 
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.do { color: #ba2121; font-style: italic; } 
code span.dt { color: #902000; } 
code span.dv { color: #40a070; } 
code span.er { color: #ff0000; font-weight: bold; } 
code span.ex { } 
code span.fl { color: #40a070; } 
code span.fu { color: #06287e; } 
code span.im { color: #008000; font-weight: bold; } 
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.kw { color: #007020; font-weight: bold; } 
code span.op { color: #666666; } 
code span.ot { color: #007020; } 
code span.pp { color: #bc7a00; } 
code span.sc { color: #4070a0; } 
code span.ss { color: #bb6688; } 
code span.st { color: #4070a0; } 
code span.va { color: #19177c; } 
code span.vs { color: #4070a0; } 
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } 
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">iperform</h1>



<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>Décrire, résumer, modéliser et prédire font partie des principaux
objectifs poursuivis lors de l’analyse d’une série temporelle. L’étape
de la description, comme pour toutes les données, consiste souvent à des
représentations graphiques telles que le chronogramme, l’histogramme, le
diagramme retardé, et aux calculs des statistiques issuelles telles que
la moyenne, la variance, le coefﬁcients d’aplatissement et
d’asymétrie.</p>
<p>Dans les domaines de finance, de comptabilité ou de marketing
opérationnel, les experts suivent au quotidien l’évolution de leurs
activités en comparant à chaque fois les résultats d’une date (ou d’une
période) par rapport à une date (ou une période) antérieure, par rapport
aux résultats du marché global ou par rapport aux résultats de leurs
concurrents directs. On parle là de concept de <em>performance</em>.</p>
<p>Si on note par <span class="math inline">\(x_t\)</span> ~ <span class="math inline">\(\left\{x_t : t = 1, · · · , n\right\}\)</span> une
série temporelle où <span class="math inline">\(t\)</span> represente le
temps, les performances les plus souvent sont :</p>
<ul>
<li><p>La performance <em>year-to-date</em> (YTD) : qui conrespond au
résultat cumulé commençant le premier jour de l’année civile ou de
l’exercice en cours jusqu’à la date actuelle, <span class="math display">\[YTD_x = \sum_{t=1}^{n} x_{t}\]</span> <span class="math inline">\(x_1\)</span> correspond à la valeur de la série au
1er janvier, et <span class="math inline">\(x_n\)</span> à la valeur de
la série à la date actuelle.</p></li>
<li><p>La performance <em>month-to-date</em> (MTD) : qui conrespond au
résultat cumulé commençant le premier jour du mois en cours jusqu’à la
date actuelle au cours du même mois, <span class="math display">\[MTD_x
= \sum_{t=1}^{n} x_{t}\]</span> <span class="math inline">\(x_1\)</span>
correspond à la valeur de la série au 1er jour du mois, et <span class="math inline">\(x_n\)</span> à la valeur de la série à la date
actuelle au cours du même mois.</p></li>
<li><p>La performance <em>week-to-date</em> (WTD) : qui conrespond au
résultat cumulé commençant le permier jour de la semaine jusqu’à la date
actuelle au cours de la même semaine. <span class="math display">\[WTD_x
= \sum_{t=1}^{n} x_{t}\]</span> <span class="math inline">\(x_1\)</span>
correspond à la valeur de la série au 1er jour de la semaine, et <span class="math inline">\(x_n\)</span> à la valeur de la série à la date
actuelle au cours de la même semaine.</p></li>
</ul>
<p>On peut egalement parler des concepts de <em>day-to-date</em> (pour
la durée écoulée au cours d’une journée pour ceux qui suivent l’activité
par heure) ou <em>quater-to-date</em> (pour le résultat cumulé sur un
trimestre) ou encore <em>full month</em>, <em>full year</em>, etc pour
designer la totalité de la periode indiquée.</p>
<p>Ces concepts représentent à eux seuls près de 90% de l’information de
pilotage des activités des analystes du secteur bancaire, bourse,
télécommunication avant d’arriver à la modélisation et la prédiction des
résultats futurs. Avec la révolution des solutions Big Data sur la
visualisation des données, plusieurs tableaux de bord utilisent ces
concepts en combinaison avec les variations par rapport aux dates ou
periodes antérieures pour enrichir l’histoire lors de la présentation
des données, des résultats ou de la performance de l’activité.</p>
<p>Cette vignette décrit l’utilisation des differentes fonctions
offertes par le package <em>iperfom</em> pour répondre à ce besoin
devenu de plus en plus important avec la révolution des données.</p>
<p>Le package <em>iperform</em> est une boite à outil qui permet de
calculer les performances d’une série temporelle en une date ou sur une
période bien spécifique. Couplé avec le package R <em>lubridate</em>, le
package offre en cette prémière version les principales fonctions que
voici regroupées en quatre (4) catégories :</p>
<div id="les-performances" class="section level3">
<h3>Les performances</h3>
<ul>
<li><p><code>dday()</code> qui renvoie la valeur d’une série à une date
donnée en argument,</p></li>
<li><p><code>wtd()</code> qui renvoie la somme des valeurs de la série
depuis le début de la semaine correspondante à la date renseignée en
argurment,</p></li>
<li><p><code>mtd()</code> qui renvoie la somme des valeurs de la série
depuis le début du mois correspondant à la date renseignée en
argurment,</p></li>
<li><p><code>qtd()</code> qui renvoie la somme des valeurs de la série
depuis le début du trimestre correspondant à la date renseignée en
argurment,</p></li>
<li><p><code>ytd()</code> qui renvoie la somme des valeurs de la série
depuis le début de l’année correspondante à la date renseignée en
argurment,</p></li>
<li><p><code>full_m()</code> qui renvoie la somme des valeurs de la
série depuis sur tout le mois correspondant à la date renseignée en
argurment.</p></li>
</ul>
</div>
<div id="les-aperçus" class="section level3">
<h3>Les aperçus</h3>
<ul>
<li><code>overview()</code> qui renvoie à l’image de la fonction
<code>summary()</code>, un résumé des performances couplées avec des
comparaisons par rapport aux périodes antérieures de la série.</li>
</ul>
</div>
<div id="les-prévisions" class="section level3">
<h3>Les prévisions</h3>
<ul>
<li><code>forecast_m()</code> qui renvoie une somme estimée sur une
période de la série en tenant compte de la performance
<em>month-to-date</em>. La fonction comprend un argument qui permet
d’utiliser un modèle spécifique de prédiction.</li>
</ul>
</div>
<div id="les-transformations" class="section level3">
<h3>Les transformations</h3>
<ul>
<li><code>mean_m()</code>qui renvoie un nouveau jeu des données créé
après transformation de la série intiales.</li>
</ul>
<p>Dans cette vignette, on présente les mecanismes des calculs derrière
ces fonctions.</p>
</div>
</div>
<div id="exemples" class="section level2">
<h2>Exemples</h2>
<p>Pour commencer, nous allons charger quelques packages nécessaires
dont nous avons besoin</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(iperform)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
<div id="description-des-données" class="section level3">
<h3>0. Description des données</h3>
<p>Nous allons illustré le fonctionnement de ces fonctions à l’aide d’un
jeu de données contenant les indicateurs de l’activité du service voix
mobile d’un operateur de téléphonie mobile anonyme.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a><span class="fu">data</span>(voix_mobile)</span></code></pre></div>
<p>Ce jeu des données contient 4 variables :</p>
<ul>
<li><p><code>date</code>, variable de type date qui part du 1er janvier
2021 au 30 septembre 2023,</p></li>
<li><p><code>Parc</code>, variable de type numeric qui renseigne le
nombre des clients qui ont effectué au moin un appel sortant,</p></li>
<li><p><code>Usage</code>, variable de type numeric qui renseigne le
nombre des minutes consommées par l’ensemble des clients lors des
appels, et</p></li>
<li><p><code>Revenu</code>, variable de type numeric qui renseigne le
revenu généré par les usages des clients à un tarif quelconque.</p></li>
</ul>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="fu">head</span>(voix_mobile)</span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a><span class="co">#&gt;         date Parc    Usage Revenu</span></span>
<span id="cb3-3"><a href="#cb3-3" tabindex="-1"></a><span class="co">#&gt; 1 2021-01-01 5178 10444.69 615.66</span></span>
<span id="cb3-4"><a href="#cb3-4" tabindex="-1"></a><span class="co">#&gt; 2 2021-01-02 3808  7669.21 473.96</span></span>
<span id="cb3-5"><a href="#cb3-5" tabindex="-1"></a><span class="co">#&gt; 3 2021-01-03 3527  7099.51 437.71</span></span>
<span id="cb3-6"><a href="#cb3-6" tabindex="-1"></a><span class="co">#&gt; 4 2021-01-04 3932  7920.70 486.31</span></span>
<span id="cb3-7"><a href="#cb3-7" tabindex="-1"></a><span class="co">#&gt; 5 2021-01-05 4149  8360.29 514.61</span></span>
<span id="cb3-8"><a href="#cb3-8" tabindex="-1"></a><span class="co">#&gt; 6 2021-01-06 4146  8353.91 509.29</span></span></code></pre></div>
<p>Un petit resumé sur des données</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a><span class="fu">summary</span>(voix_mobile)</span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a><span class="co">#&gt;       date                 Parc          Usage           Revenu     </span></span>
<span id="cb4-3"><a href="#cb4-3" tabindex="-1"></a><span class="co">#&gt;  Min.   :2021-01-01   Min.   :2516   Min.   : 5051   Min.   :366.0  </span></span>
<span id="cb4-4"><a href="#cb4-4" tabindex="-1"></a><span class="co">#&gt;  1st Qu.:2021-09-08   1st Qu.:5598   1st Qu.: 9550   1st Qu.:519.5  </span></span>
<span id="cb4-5"><a href="#cb4-5" tabindex="-1"></a><span class="co">#&gt;  Median :2022-05-17   Median :7025   Median :10671   Median :557.0  </span></span>
<span id="cb4-6"><a href="#cb4-6" tabindex="-1"></a><span class="co">#&gt;  Mean   :2022-05-17   Mean   :6625   Mean   :10546   Mean   :563.5  </span></span>
<span id="cb4-7"><a href="#cb4-7" tabindex="-1"></a><span class="co">#&gt;  3rd Qu.:2023-01-22   3rd Qu.:7794   3rd Qu.:11664   3rd Qu.:603.2  </span></span>
<span id="cb4-8"><a href="#cb4-8" tabindex="-1"></a><span class="co">#&gt;  Max.   :2023-09-30   Max.   :8154   Max.   :15285   Max.   :808.8</span></span></code></pre></div>
<p>La variable <em>Revenu</em> sur quoi on va se focaliser varie de
365.96 usd à 808.79 usd, avec une moyenne de 563.5172084 usd. Elle a une
variance de 3819 et un écart type de 62. La valeur de <em>p-value &lt;
0,05</em> de la sortie du test de normalité de Shapiro ci-dessous
indique que la distribution des données est significativement différente
de la distribution normale. Voilà le peu qu’on puisse dire, hormis les
représentations graphiques sur ce qui est de la description de cette
série.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(voix_mobile<span class="sc">$</span>Revenu)</span>
<span id="cb5-2"><a href="#cb5-2" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb5-3"><a href="#cb5-3" tabindex="-1"></a><span class="co">#&gt;  Shapiro-Wilk normality test</span></span>
<span id="cb5-4"><a href="#cb5-4" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb5-5"><a href="#cb5-5" tabindex="-1"></a><span class="co">#&gt; data:  voix_mobile$Revenu</span></span>
<span id="cb5-6"><a href="#cb5-6" tabindex="-1"></a><span class="co">#&gt; W = 0.98597, p-value = 3.215e-08</span></span></code></pre></div>
</div>
<div id="la-fonction-dday" class="section level3">
<h3>1. La fonction <em>dday()</em></h3>
<p>Pour connaitre le <code>Revenu</code> que l’ensemble des clients ont
généré en date du <em>11 août 2023</em>, on utilise la fonction
<code>dday()</code> comme suit :</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a><span class="fu">dday</span>(<span class="at">data =</span> voix_mobile,</span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a>      <span class="at">date =</span> <span class="st">&quot;2023-08-11&quot;</span>,</span>
<span id="cb6-3"><a href="#cb6-3" tabindex="-1"></a>      <span class="at">d =</span> <span class="dv">0</span>,</span>
<span id="cb6-4"><a href="#cb6-4" tabindex="-1"></a>      <span class="at">x =</span> <span class="st">&quot;Revenu&quot;</span>,</span>
<span id="cb6-5"><a href="#cb6-5" tabindex="-1"></a>      <span class="at">unite =</span> <span class="dv">1</span>,</span>
<span id="cb6-6"><a href="#cb6-6" tabindex="-1"></a>      <span class="at">decimal =</span> <span class="dv">0</span>)</span>
<span id="cb6-7"><a href="#cb6-7" tabindex="-1"></a><span class="co">#&gt; [1] 569</span></span></code></pre></div>
<p>Les arguments de la fonction</p>
<ul>
<li><p><code>data</code> le jeu des données qui contient l’ensemble des
données à exploiter,</p></li>
<li><p><code>date</code> un character qui renseine la date à laquelle on
cherche l’information,</p></li>
<li><p><code>d</code> un entier qui determine le decalage des jours à
prendre, la valeur par défaut vaut <code>0</code>. si <code>d=1</code>,
on prendra la date du <em>10 août 2023</em>,</p></li>
<li><p><code>unite</code> un numeric qui renseigne l’echel des valeurs
qu’on souhaite avoir. sa valeur par defaut vaut <code>1</code>. Si
<code>unite=1000</code>, la fonction va renvoyer une valeur diviser par
<code>1000</code>, et</p></li>
<li><p><code>decimal</code> un entier designant le nombre de chiffre
après la virgule qu’on souhaite afficher si le résultat est un decimal.
Sa valeur par défaut vaut <code>0</code>.</p></li>
</ul>
</div>
<div id="la-fonction-mtd" class="section level3">
<h3>2. La fonction <em>mtd()</em></h3>
<p>Pour connaître la performance <em>month-to-date</em> du revenu
réalisée en date du <em>11 août 2023</em>, c’est-à-dire la somme des
valeurs partant du <em>01 août 2023</em> au <em>11 août 2023</em>
inclus, on utilise la fonction <code>mtd()</code> comme suit :</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a><span class="fu">mtd</span>(<span class="at">data =</span> voix_mobile,</span>
<span id="cb7-2"><a href="#cb7-2" tabindex="-1"></a>    <span class="at">date =</span> <span class="st">&quot;2023-08-11&quot;</span>,</span>
<span id="cb7-3"><a href="#cb7-3" tabindex="-1"></a>    <span class="at">m =</span> <span class="dv">0</span>,</span>
<span id="cb7-4"><a href="#cb7-4" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Revenu&quot;</span>,</span>
<span id="cb7-5"><a href="#cb7-5" tabindex="-1"></a>    <span class="at">unite =</span> <span class="dv">1</span>,</span>
<span id="cb7-6"><a href="#cb7-6" tabindex="-1"></a>    <span class="at">decimal =</span> <span class="dv">0</span>)</span>
<span id="cb7-7"><a href="#cb7-7" tabindex="-1"></a><span class="co">#&gt; [1] 6100</span></span></code></pre></div>
<p>ici, seul l’argument <code>m</code> est nouveau, les autres ont la
même utilité que pour la fonction <code>dday()</code>.</p>
<ul>
<li><code>m</code> un entier qui determine le decalage du mois à
prendre, la valeur par défaut vaut <code>0</code>. si <code>m=1</code>,
on prendra la date du <em>11 juillet 2023</em>.</li>
</ul>
</div>
<div id="la-fonction-ytd" class="section level3">
<h3>3. La fonction <em>ytd()</em></h3>
<p>Pour connaître la performance <em>year-to-date</em> du revenu
réalisée en date du <em>11 août 2023</em>, c’est-à-dire la somme des
valeurs partant du <em>01 janvier 2023</em> au <em>11 août 2023</em>
inclus, on utilise la fonction <code>ytd()</code> comme suit :</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="fu">ytd</span>(<span class="at">data =</span> voix_mobile,</span>
<span id="cb8-2"><a href="#cb8-2" tabindex="-1"></a>    <span class="at">date =</span> <span class="st">&quot;2023-08-11&quot;</span>,</span>
<span id="cb8-3"><a href="#cb8-3" tabindex="-1"></a>    <span class="at">a =</span> <span class="dv">0</span>,</span>
<span id="cb8-4"><a href="#cb8-4" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Revenu&quot;</span>,</span>
<span id="cb8-5"><a href="#cb8-5" tabindex="-1"></a>    <span class="at">unite =</span> <span class="dv">1000</span>,</span>
<span id="cb8-6"><a href="#cb8-6" tabindex="-1"></a>    <span class="at">decimal =</span> <span class="dv">0</span>)</span>
<span id="cb8-7"><a href="#cb8-7" tabindex="-1"></a><span class="co">#&gt; [1] 123</span></span></code></pre></div>
<p>idem pour les arguments.</p>
<ul>
<li><code>a</code> un entier qui determine le decalage de l’année à
prendre, la valeur par défaut vaut <code>0</code>. Si <code>a=1</code>,
on prendra la date du <em>11 août 2022</em>.</li>
</ul>
</div>
<div id="la-fonction-wtd" class="section level3">
<h3>4. La fonction <em>wtd()</em></h3>
<p>Pour connaître la performance <em>week-to-date</em> du revenu
réalisée en date du <em>11 août 2023</em>, on part du fait que la date
<em>11 août 2023</em> est un vendredi, donc le 6e de la semaine en
considerant le dimanche <em>06 août 2023</em> comme 1er jour. Ainsi, on
calcule la somme des valeurs partant du <em>06</em> au <em>11</em>
inclus en utilisant la fonction <code>wtd()</code> comme suit :</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a><span class="fu">wtd</span>(<span class="at">data =</span> voix_mobile,</span>
<span id="cb9-2"><a href="#cb9-2" tabindex="-1"></a>    <span class="at">date =</span> <span class="st">&quot;2023-08-11&quot;</span>,</span>
<span id="cb9-3"><a href="#cb9-3" tabindex="-1"></a>    <span class="at">w =</span> <span class="dv">0</span>,</span>
<span id="cb9-4"><a href="#cb9-4" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Revenu&quot;</span>,</span>
<span id="cb9-5"><a href="#cb9-5" tabindex="-1"></a>    <span class="at">unite =</span> <span class="dv">1</span>,</span>
<span id="cb9-6"><a href="#cb9-6" tabindex="-1"></a>    <span class="at">decimal =</span> <span class="dv">0</span>)</span>
<span id="cb9-7"><a href="#cb9-7" tabindex="-1"></a><span class="co">#&gt; [1] 3348</span></span></code></pre></div>
<p>idem pour les arguments.</p>
<ul>
<li><code>w</code> un entier qui determine le decalage de la semaine à
prendre, la valeur par défaut vaut <code>0</code>. Si <code>w=1</code>,
on prendra la date du vendredi <em>4 août 2022</em>.</li>
</ul>
</div>
<div id="la-fonction-full_m" class="section level3">
<h3>5. La fonction <em>full_m()</em></h3>
<p>Cette fonction calcule la somme des valeurs d’une série au cours d’un
mois. Le mois est déterminé par la date qu’on passe en argument à la
fonction. Ainsi le code ci-dessous va nous renvoyer le total jusqu’en
date du <em>31 août 2023</em> :</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a><span class="fu">full_m</span>(<span class="at">data =</span> voix_mobile,</span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a>       <span class="at">date =</span> <span class="st">&quot;2023-08-11&quot;</span>,</span>
<span id="cb10-3"><a href="#cb10-3" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Revenu&quot;</span>,</span>
<span id="cb10-4"><a href="#cb10-4" tabindex="-1"></a>       <span class="at">unite =</span> <span class="dv">1000</span>,</span>
<span id="cb10-5"><a href="#cb10-5" tabindex="-1"></a>       <span class="at">decimal =</span> <span class="dv">0</span>,</span>
<span id="cb10-6"><a href="#cb10-6" tabindex="-1"></a>       <span class="at">cumul =</span> <span class="cn">FALSE</span>)</span>
<span id="cb10-7"><a href="#cb10-7" tabindex="-1"></a><span class="co">#&gt; [1] 16</span></span></code></pre></div>
<p>Et cela quelque soit la date qu’on introduit en argument si cette
dernière est comprise entre <em>01 août 2023</em> et <em>31 août
2023</em>. On peut le verifier avec le code ci-dessous :</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a><span class="fu">full_m</span>(<span class="at">data =</span> voix_mobile,</span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a>       <span class="at">date =</span> <span class="st">&quot;2023-08-25&quot;</span>,</span>
<span id="cb11-3"><a href="#cb11-3" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Revenu&quot;</span>,</span>
<span id="cb11-4"><a href="#cb11-4" tabindex="-1"></a>       <span class="at">unite =</span> <span class="dv">1000</span>)</span>
<span id="cb11-5"><a href="#cb11-5" tabindex="-1"></a><span class="co">#&gt; [1] 16</span></span></code></pre></div>
</div>
<div id="la-fonction-forecast_m" class="section level3">
<h3>6. La fonction <em>forecast_m()</em></h3>
<p>Pour cette version du package, la fonction <code>forecast_m()</code>
ne fait pas grande chose, si ce n’est de calculer le total qu’on
pourrait avoir sur un mois, connaissant sa performance
<em>month-to-date</em> et le nombre du jour restant dans le même mois.
Par exemple, si on place à la date du <em>2023-08-11</em>, le forecast
en cette date vaut :</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a><span class="fu">forecast_m</span>(<span class="at">data =</span> voix_mobile,</span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a>           <span class="at">date =</span> <span class="st">&quot;2023-08-11&quot;</span>,</span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a>           <span class="at">x =</span> <span class="st">&quot;Revenu&quot;</span>,</span>
<span id="cb12-4"><a href="#cb12-4" tabindex="-1"></a>           <span class="at">unite =</span> <span class="dv">1000</span>,</span>
<span id="cb12-5"><a href="#cb12-5" tabindex="-1"></a>           <span class="at">decimal =</span> <span class="dv">0</span>,</span>
<span id="cb12-6"><a href="#cb12-6" tabindex="-1"></a>           <span class="at">cumul =</span> <span class="cn">FALSE</span>,</span>
<span id="cb12-7"><a href="#cb12-7" tabindex="-1"></a>           <span class="at">mod =</span> <span class="st">&quot;NULL&quot;</span>) </span>
<span id="cb12-8"><a href="#cb12-8" tabindex="-1"></a><span class="co">#&gt; [1] 17</span></span></code></pre></div>
<p>En constate que cette valeur sera différente en fonction de la date à
laquelle on se place au cours du mois :</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a>vec_date <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;2023-08-20&quot;</span>, <span class="st">&quot;2023-08-25&quot;</span>, <span class="st">&quot;2023-08-28&quot;</span>, <span class="st">&quot;2023-08-30&quot;</span>, <span class="st">&quot;2023-08-31&quot;</span>)</span>
<span id="cb13-2"><a href="#cb13-2" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" tabindex="-1"></a><span class="cf">for</span> (d <span class="cf">in</span> vec_date) {</span>
<span id="cb13-4"><a href="#cb13-4" tabindex="-1"></a>  F <span class="ot">=</span> <span class="fu">forecast_m</span>(<span class="at">data =</span> voix_mobile,</span>
<span id="cb13-5"><a href="#cb13-5" tabindex="-1"></a>             <span class="at">date =</span> d,</span>
<span id="cb13-6"><a href="#cb13-6" tabindex="-1"></a>             <span class="at">x =</span> <span class="st">&quot;Revenu&quot;</span>,</span>
<span id="cb13-7"><a href="#cb13-7" tabindex="-1"></a>             <span class="at">unite =</span> <span class="dv">1000</span>)</span>
<span id="cb13-8"><a href="#cb13-8" tabindex="-1"></a>  <span class="fu">print</span>(F)</span>
<span id="cb13-9"><a href="#cb13-9" tabindex="-1"></a>  }</span>
<span id="cb13-10"><a href="#cb13-10" tabindex="-1"></a><span class="co">#&gt; [1] 17</span></span>
<span id="cb13-11"><a href="#cb13-11" tabindex="-1"></a><span class="co">#&gt; [1] 16</span></span>
<span id="cb13-12"><a href="#cb13-12" tabindex="-1"></a><span class="co">#&gt; [1] 16</span></span>
<span id="cb13-13"><a href="#cb13-13" tabindex="-1"></a><span class="co">#&gt; [1] 16</span></span>
<span id="cb13-14"><a href="#cb13-14" tabindex="-1"></a><span class="co">#&gt; [1] 16</span></span></code></pre></div>
<p>L’arguments <code>mod</code></p>
<ul>
<li><code>mod</code>, un character qui determine le type de modèle à
utiliser pour faire la prediction. Sa valeur par defaut est
<code>NULL</code> et l’alternative ne fait pas l’objet de cette
version.</li>
</ul>
<p>Mais au moins, on constate que pour ce modèle, plus on donne en
argument une date qui est proche de la clôture du mois, plus la fonction
renvoit une valeur proche de la fonction <code>full_m</code>.</p>
</div>
<div id="la-fonction-overview" class="section level3">
<h3>7. La fonction <em>overview()</em></h3>
<p>On a l’habitude d’utiliser la fonction de base <code>summary()</code>
qui renvoie les statistiques issuelles, cependant ces paramètres entrent
rarement dans le narratif des analystes des données du secteur
susmentionnés. Pour reporter les résultats, les experts presentent des
apercus globaux ou ils parlent des performances <em>YTD</em>,
<em>MTD</em>, <em>WTD</em>, etc… et leurs comparaisons par rapport aux
périodes antérieures.</p>
<p>Rappellons ici quelques concepts des comparaisons :</p>
<ul>
<li><p>La comparaison <em>DoD</em> en date du <em>2023-08-11</em> : elle
consiste à calculer la variation du revenu en cette date par rapport à
la date du <em>2023-08-10</em>, c-est-à-dire: <span class="math display">\[DoD = \frac{dday -
dday_1}{dday}\]</span></p></li>
<li><p>La comparaison <em>SPLM</em> en date du <em>2023-08-11</em> :
elle consite à calculer la variation <em>MTD</em> au <em>2023-08-11</em>
par rapport au <em>MTD</em> en date du <em>2023-07-11</em> (on note
souvent par <span class="math inline">\(MTD_1\)</span>) : <span class="math display">\[SLPM = \frac{MTD - MTD_1}{MTD}\]</span></p></li>
<li><p>La performance <em>YoY</em> en date du <em>2023-08-11</em> : elle
consite à calculer la variation <em>YTD</em> au <em>2023-08-11</em> par
rapport au <em>YTD</em> en date du <em>2022-08-11</em> (on note souvent
par <span class="math inline">\(YTD_1\)</span>) : <span class="math display">\[YoY = \frac{YTD - YTD_1}{YTD}\]</span></p></li>
</ul>
<p>On parle aussi de la comparaison <em>WoW</em>, <em>MoM</em>, etc.</p>
<p>Ainsi, si on souhaite avoir un aperçu du revenu en date du
<em>2023-08-11</em>, on utilise la fonction <code>overview()</code>
comme suit :</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a><span class="fu">overview</span>(<span class="at">data =</span> voix_mobile,</span>
<span id="cb14-2"><a href="#cb14-2" tabindex="-1"></a>         <span class="at">date =</span> <span class="st">&quot;2023-08-11&quot;</span>,</span>
<span id="cb14-3"><a href="#cb14-3" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">&quot;Revenu&quot;</span>,</span>
<span id="cb14-4"><a href="#cb14-4" tabindex="-1"></a>         <span class="at">unite =</span> <span class="dv">1</span>,</span>
<span id="cb14-5"><a href="#cb14-5" tabindex="-1"></a>         <span class="at">decimal =</span> <span class="dv">2</span>,</span>
<span id="cb14-6"><a href="#cb14-6" tabindex="-1"></a>         <span class="at">cumul =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>Lecture de la sortie du code R :</p>
<pre><code>#&gt;   Facteur DDay7 DDay   DoD WTD1  WTD  WoW MTD1  MTD SPLM Full_M FORECAST  MoM
#&gt; 1  Revenu   577  569 -1.39 3228 3348 3.72 6035 6100 1.08  16308    17191 5.41
#&gt;     YTD1    YTD   SPLY
#&gt; 1 137302 122850 -10.53</code></pre>
<p>On pourra par exemple dire :</p>
<p>En date du <em>2023-08-11</em>, l’operateur mobile a réalisé un
chiffre d’affaire de 6100 usd en MTD, soit une hausse de 1.08% comparé à
la même periode du mois passé. Avec le nombre de jours restant au cours
du mois, on prévoit un total de 1.7191^{4} usd à la fin mois, ce qui
fera une hausse de 5.41% par rapport à tout le mois de Juillet. En
outre, la performance year-to-date atteint 1.2285^{5} usd, soit une
baisse de -10.53% par rapport à l’année passée.</p>
<p>Certe, ce discours ne represente pas les causes qui expliquent les
resultats en chaque période ni les différentes variations, mais au
moins, raconte une histoire évolutive et un aperçu global de la
perfomance de l’activité. Il ne restera qu’au rapporteur d’enrichir son
histoire avec les resultats des analyses des causes à effet.</p>
</div>
<div id="la-fonction-mean_m" class="section level3">
<h3>8. La fonction <em>mean_m()</em></h3>
<p>Cette fonction transforme une série temporelle à une série de moyenne
mobile où chaque terme de la série devient la moyenne de lui-même avec
ses sept(6) derniers termes précédants. A la sortie, la fonction renvoie
un jeu des données où chaque colonne renseigne les données d’une année
pour être superposées sur un graphe.</p>
<p>Exemple d’utilisation</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a>df_mb <span class="ot">=</span> <span class="fu">mean_m</span>(<span class="at">data =</span> voix_mobile, </span>
<span id="cb16-2"><a href="#cb16-2" tabindex="-1"></a>               <span class="at">x =</span> <span class="st">&quot;Revenu&quot;</span>,</span>
<span id="cb16-3"><a href="#cb16-3" tabindex="-1"></a>               <span class="at">unite =</span> <span class="dv">1</span>,</span>
<span id="cb16-4"><a href="#cb16-4" tabindex="-1"></a>               <span class="at">decimal =</span> <span class="dv">0</span>)</span>
<span id="cb16-5"><a href="#cb16-5" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" tabindex="-1"></a><span class="fu">head</span>(df_mb, <span class="dv">10</span>)</span>
<span id="cb16-7"><a href="#cb16-7" tabindex="-1"></a><span class="co">#&gt;          date Min 2021 2022 2023 Max</span></span>
<span id="cb16-8"><a href="#cb16-8" tabindex="-1"></a><span class="co">#&gt; 1  2023-01-01 616  616  675  645 675</span></span>
<span id="cb16-9"><a href="#cb16-9" tabindex="-1"></a><span class="co">#&gt; 2  2023-01-02 545  545  587  633 633</span></span>
<span id="cb16-10"><a href="#cb16-10" tabindex="-1"></a><span class="co">#&gt; 3  2023-01-03 509  509  584  625 625</span></span>
<span id="cb16-11"><a href="#cb16-11" tabindex="-1"></a><span class="co">#&gt; 4  2023-01-04 503  503  573  615 615</span></span>
<span id="cb16-12"><a href="#cb16-12" tabindex="-1"></a><span class="co">#&gt; 5  2023-01-05 506  506  577  613 613</span></span>
<span id="cb16-13"><a href="#cb16-13" tabindex="-1"></a><span class="co">#&gt; 6  2023-01-06 506  506  580  612 612</span></span>
<span id="cb16-14"><a href="#cb16-14" tabindex="-1"></a><span class="co">#&gt; 7  2023-01-07 506  506  581  608 608</span></span>
<span id="cb16-15"><a href="#cb16-15" tabindex="-1"></a><span class="co">#&gt; 8  2023-01-08 491  491  568  591 591</span></span>
<span id="cb16-16"><a href="#cb16-16" tabindex="-1"></a><span class="co">#&gt; 9  2023-01-09 495  495  569  588 588</span></span>
<span id="cb16-17"><a href="#cb16-17" tabindex="-1"></a><span class="co">#&gt; 10 2023-01-10 497  497  575  587 587</span></span></code></pre></div>
<ul>
<li><p>Tous les arguments ont le même sens sens que dans les fonctions
précédentes,</p></li>
<li><p>La colonne date est de longueur <code>n</code> inférieur ou egale
à <code>365</code>. Elle depend de l’etendue de la période du jeu des
données initial,</p></li>
<li><p>Les moyennes calculées sont classées par année civiles, autant on
a des années, autant on aura des colonnes,</p></li>
<li><p>L’argument <code>borne</code> permet de masquer la colonne
<code>Min</code> et <code>Max</code> de chaque ligne.</p></li>
</ul>
</div>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
